In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [60]:
from sklearn.datasets import load_wine

In [61]:
data=load_wine()
data

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:                          1.36  3.23    2.36  0.27\n    Alcalinity of Ash:            10.6  30.0    19.5   3.3\n    Magnesium:                    70.0 162.0    99.7  14.3\n    Total Phenols:                0.98  3.88    2.29  0.63\n    Flavanoids:                   0.34  5.08    2.03  1.00\n    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12\n    Proanthocyanins:              0.41  3.58    1.59  0.57\n    Colour Intensity:              1.3  13.0     5.1   2.3\n    Hue:                          0.48  1.71    0.96  0.23\n    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71\n    Proline:                       278  1680     746   315\n    ============================= ==== ===== ======= =====\n\n    :Missing Attribute Values: None\n    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)\n    :Creator: R.A. Fisher\n    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n    :Date: July, 1988\n\nThis is a copy of UCI ML Wine recognition datasets.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data\n\nThe data is the results of a chemical analysis of wines grown in the same\nregion in Italy by three different cultivators. There are thirteen different\nmeasurements taken for different constituents found in the three types of\nwine.\n\nOriginal Owners: \n\nForina, M. et al, PARVUS - \nAn Extendible Package for Data Exploration, Classification and Correlation. \nInstitute of Pharmaceutical and Food Analysis and Technologies,\nVia Brigata Salerno, 16147 Genoa, Italy.\n\nCitation:\n\nLichman, M. (2013). UCI Machine Learning Repository\n[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,\nSchool of Information and Computer Science. \n\n.. topic:: References\n\n  (1) S. Aeberhard, D. Coomans and O. de Vel, \n  Comparison of Classifiers in High Dimensional Settings, \n  Tech. Rep. no. 92-02, (1992), Dept. of Computer Science and Dept. of  \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Technometrics). \n\n  The data was used with many others for comparing various \n  classifiers. The classes are separable, though only RDA \n  has achieved 100% correct classification. \n  (RDA : 100%, QDA 99.4%, LDA 98.9%, 1NN 96.1% (z-transformed data)) \n  (All results using the leave-one-out technique) \n\n  (2) S. Aeberhard, D. Coomans and O. de Vel, \n  "THE CLASSIFICATION PERFORMANCE OF RDA" \n  Tech. Rep. no. 92-01, (1992), Dept. of Computer Science and Dept. of \n  Mathematics and Statistics, James Cook University of North Queensland. \n  (Also submitted to Journal of Chemometrics).\n',
 'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'feature_names': ['alcohol',
  'malic_acid',
  'ash',
  'alcalinity_of_ash',
  'magnesium',
  'total_phenols',
  'flavanoids',
  'nonflavanoid_phenols',
  'proanthocyanins',
  'color_intensity',
  'hue',
  'od280/od315_of_diluted_wines',
  'proline'],
 'frame': None,
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2]),
 'target_names': array(['class_0', 'class_1', 'class_2'], dtype='<U7')}

In [62]:
data1=pd.DataFrame(data['data'],columns=data['feature_names'])

In [63]:
data1

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [64]:
data1['class']=data['target']

In [65]:
data1

     alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  class
0      14.23        1.71  2.43  ...                          3.92   1065.0      0
1      13.20        1.78  2.14  ...                          3.40   1050.0      0
2      13.16        2.36  2.67  ...                          3.17   1185.0      0
3      14.37        1.95  2.50  ...                          3.45   1480.0      0
4      13.24        2.59  2.87  ...                          2.93    735.0      0
..       ...         ...   ...  ...                           ...      ...    ...
173    13.71        5.65  2.45  ...                          1.74    740.0      2
174    13.40        3.91  2.48  ...                          1.56    750.0      2
175    13.27        4.28  2.26  ...                          1.56    835.0      2
176    13.17        2.59  2.37  ...                          1.62    840.0      2
177    14.13        4.10  2.74  ...                          1.60    560.0      2

[178 rows x 14 columns]

In [66]:
data1['class']=data1['class'].replace(to_replace=[0,1,2],value=['class_0','class_1','class_2'])

In [67]:
data1

     alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline    class
0      14.23        1.71  2.43  ...                          3.92   1065.0  class_0
1      13.20        1.78  2.14  ...                          3.40   1050.0  class_0
2      13.16        2.36  2.67  ...                          3.17   1185.0  class_0
3      14.37        1.95  2.50  ...                          3.45   1480.0  class_0
4      13.24        2.59  2.87  ...                          2.93    735.0  class_0
..       ...         ...   ...  ...                           ...      ...      ...
173    13.71        5.65  2.45  ...                          1.74    740.0  class_2
174    13.40        3.91  2.48  ...                          1.56    750.0  class_2
175    13.27        4.28  2.26  ...                          1.56    835.0  class_2
176    13.17        2.59  2.37  ...                          1.62    840.0  class_2
177    14.13        4.10  2.74  ...                          1.60    560.0  class_2

[178 rows x 14 columns]

In [76]:
from sklearn.model_selection import train_test_split
x=data1.iloc[:,0:-1]
y=data1.iloc[:,13:14]
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=1)

In [77]:
xtrain

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
91     12.00        1.51  2.42  ...  1.05                          2.65    450.0
81     12.72        1.81  2.20  ...  1.16                          3.14    714.0
114    12.08        1.39  2.50  ...  0.93                          3.19    385.0
48     14.10        2.02  2.40  ...  1.07                          2.75   1060.0
54     13.74        1.67  2.25  ...  0.92                          3.20   1060.0
..       ...         ...   ...  ...   ...                           ...      ...
133    12.70        3.55  2.36  ...  0.78                          1.29    600.0
137    12.53        5.51  2.64  ...  0.82                          1.69    515.0
72     13.49        1.66  2.24  ...  0.98                          2.78    472.0
140    12.93        2.81  2.70  ...  0.77                          2.31    600.0
37     13.05        1.65  2.55  ...  1.12                          2.51   1105.0

[142 rows x 13 columns]

In [78]:
ytrain

       class
91   class_1
81   class_1
114  class_1
48   class_0
54   class_0
..       ...
133  class_2
137  class_2
72   class_1
140  class_2
37   class_0

[142 rows x 1 columns]

In [79]:
xtest

     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
161    13.69        3.26  2.54  ...  0.96                          1.82    680.0
117    12.42        1.61  2.19  ...  1.06                          2.96    345.0
19     13.64        3.10  2.56  ...  0.96                          3.36    845.0
69     12.21        1.19  1.75  ...  1.28                          3.07    718.0
53     13.77        1.90  2.68  ...  1.13                          2.93   1375.0
138    13.49        3.59  2.19  ...  0.81                          1.82    580.0
112    11.76        2.68  2.92  ...  1.23                          2.50    607.0
14     14.38        1.87  2.38  ...  1.20                          3.00   1547.0
160    12.36        3.83  2.38  ...  0.56                          1.58    520.0
107    12.72        1.75  2.28  ...  0.88                          2.42    488.0
11     14.12        1.48  2.32  ...  1.17                          2.82   1280.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
108    12.22        1.29  1.94  ...  0.86                          3.02    312.0
42     13.88        1.89  2.59  ...  0.88                          3.56   1095.0
84     11.84        0.89  2.58  ...  0.79                          3.08    520.0
113    11.41        0.74  2.50  ...  1.10                          2.31    434.0
152    13.11        1.90  2.75  ...  0.61                          1.33    425.0
35     13.48        1.81  2.41  ...  1.04                          3.47    920.0
105    12.42        2.55  2.27  ...  0.86                          3.30    315.0
31     13.58        1.66  2.36  ...  1.09                          2.88   1515.0
51     13.83        1.65  2.60  ...  1.24                          3.37   1265.0
126    12.43        1.53  2.29  ...  0.69                          2.84    352.0
130    12.86        1.35  2.32  ...  0.76                          1.29    630.0
73     12.99        1.67  2.60  ...  1.31                          3.50    985.0
40     13.56        1.71  2.31  ...  0.95                          3.38    795.0
162    12.85        3.27  2.58  ...  0.87                          2.11    570.0
47     13.90        1.68  2.12  ...  0.91                          3.33    985.0
29     14.02        1.68  2.21  ...  1.04                          3.59   1035.0
16     14.30        1.92  2.72  ...  1.07                          2.65   1280.0
147    12.87        4.61  2.48  ...  0.54                          1.86    625.0
97     12.29        1.41  1.98  ...  1.23                          2.74    428.0
159    13.48        1.67  2.64  ...  0.57                          1.78    620.0
151    12.79        2.67  2.48  ...  0.48                          1.47    480.0
5      14.20        1.76  2.45  ...  1.05                          2.85   1450.0
120    11.45        2.40  2.42  ...  0.80                          3.39    625.0
94     11.62        1.99  2.28  ...  1.16                          2.96    345.0

[36 rows x 13 columns]

In [80]:
xtrain.shape

(142, 13)

In [81]:
ytrain.shape

(142, 1)

In [82]:
xtest.shape

(36, 13)

In [83]:
ytest.shape

(36, 1)

In [84]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
scaler=MinMaxScaler()
xtrain_transform=scaler.fit_transform(xtrain)
xtest_transform=scaler.fit_transform(xtest)
xtrain_transform[:10]

array([[0.25526316, 0.1244898 , 0.56684492, 0.63687151, 0.17391304,
        0.16206897, 0.19198312, 0.74      , 0.38485804, 0.19795222,
        0.43103448, 0.50549451, 0.12268188],
       [0.44473684, 0.18571429, 0.44919786, 0.45810056, 0.17391304,
        0.42068966, 0.46202532, 0.26      , 0.42902208, 0.22354949,
        0.52586207, 0.68498168, 0.31098431],
       [0.27631579, 0.1       , 0.60962567, 0.66480447, 0.15217391,
        0.54482759, 0.41139241, 0.6       , 0.19873817, 0.13822526,
        0.32758621, 0.7032967 , 0.07631954],
       [0.80789474, 0.22857143, 0.55614973, 0.45810056, 0.35869565,
        0.61034483, 0.5443038 , 0.38      , 0.6214511 , 0.41979522,
        0.44827586, 0.54212454, 0.55777461],
       [0.71315789, 0.15714286, 0.47593583, 0.32402235, 0.52173913,
        0.55862069, 0.54008439, 0.16      , 0.38170347, 0.38993174,
        0.31896552, 0.70695971, 0.55777461],
       [0.35263158, 0.00816327, 0.        , 0.        , 0.19565217,
        0.34482759, 0.04852321, 0.3       , 0.00315457, 0.05716724,
        0.43103448, 0.2014652 , 0.17261056],
       [0.71052632, 0.70612245, 0.48128342, 0.66480447, 0.19565217,
        0.10344828, 0.02742616, 0.78      , 0.23343849, 0.4556314 ,
        0.19827586, 0.17582418, 0.17261056],
       [0.83947368, 0.63061224, 0.61497326, 0.1452514 , 0.63043478,
        0.69655172, 0.56962025, 0.14      , 0.52681388, 0.32593857,
        0.29310345, 0.82783883, 0.34379458],
       [0.83947368, 0.16326531, 0.5026738 , 0.31843575, 0.52173913,
        0.76551724, 0.56118143, 0.26      , 0.51104101, 0.43515358,
        0.3362069 , 0.74725275, 0.4935806 ],
       [0.53157895, 0.17755102, 0.39572193, 0.3575419 , 0.40217391,
        0.69655172, 0.56118143, 0.3       , 0.51104101, 0.32081911,
        0.28448276, 0.76190476, 0.43295292]])

In [86]:
xtest_transform

array([[0.76767677, 0.65116279, 0.67521368, 0.44444444, 0.34328358,
        0.234375  , 0.02531646, 0.69230769, 0.        , 0.39422085,
        0.57831325, 0.23043478, 0.29797571],
       [0.34006734, 0.2248062 , 0.37606838, 0.58333333, 0.35820896,
        0.32291667, 0.50949367, 0.38461538, 0.375     , 0.        ,
        0.69879518, 0.72608696, 0.02672065],
       [0.75084175, 0.60981912, 0.69230769, 0.17777778, 0.47761194,
        0.6875    , 0.80696203, 0.05769231, 0.39814815, 0.31372549,
        0.57831325, 0.9       , 0.43157895],
       [0.26936027, 0.11627907, 0.        , 0.26666667, 1.        ,
        0.24479167, 0.25316456, 0.        , 0.78703704, 0.08152735,
        0.96385542, 0.77391304, 0.32874494],
       [0.79461279, 0.2997416 , 0.79487179, 0.28333333, 0.46268657,
        0.84375   , 0.73101266, 0.48076923, 0.40740741, 0.4375645 ,
        0.78313253, 0.71304348, 0.86072874],
       [0.7003367 , 0.73643411, 0.37606838, 0.41666667, 0.05970149,
        0.125     , 0.        , 0.84615385, 0.03703704, 0.37564499,
        0.39759036, 0.23043478, 0.21700405],
       [0.11784512, 0.50129199, 1.        , 0.44444444, 0.28358209,
        0.19270833, 0.49050633, 0.88461538, 0.11574074, 0.17956656,
        0.90361446, 0.52608696, 0.2388664 ],
       [1.        , 0.29198966, 0.53846154, 0.        , 0.26865672,
        1.        , 1.        , 0.28846154, 1.        , 0.56140351,
        0.86746988, 0.74347826, 1.        ],
       [0.31986532, 0.79844961, 0.53846154, 0.5       , 0.05970149,
        0.47916667, 0.13924051, 0.69230769, 0.11111111, 0.57688338,
        0.09638554, 0.12608696, 0.16842105],
       [0.44107744, 0.26098191, 0.45299145, 0.58333333, 0.        ,
        0.        , 0.40506329, 0.65384615, 0.38425926, 0.12796698,
        0.48192771, 0.49130435, 0.14251012],
       [0.91245791, 0.19121447, 0.48717949, 0.26666667, 0.1641791 ,
        0.42708333, 0.61708861, 0.23076923, 0.35648148, 0.30340557,
        0.8313253 , 0.66521739, 0.78380567],
       [0.61616162, 0.47803618, 0.95726496, 0.5       , 0.50746269,
        0.73958333, 0.69936709, 0.48076923, 0.47222222, 0.23323013,
        0.6746988 , 0.71304348, 0.34251012],
       [0.27272727, 0.14211886, 0.16239316, 0.38888889, 0.11940299,
        0.51041667, 0.49367089, 0.48076923, 0.59259259, 0.06604747,
        0.45783133, 0.75217391, 0.        ],
       [0.83164983, 0.29715762, 0.71794872, 0.16666667, 0.25373134,
        0.97395833, 0.97468354, 0.05769231, 0.41666667, 0.34778122,
        0.48192771, 0.98695652, 0.6340081 ],
       [0.14478114, 0.03875969, 0.70940171, 0.33333333, 0.14925373,
        0.42708333, 0.54746835, 0.15384615, 0.71759259, 0.10216718,
        0.37349398, 0.77826087, 0.16842105],
       [0.        , 0.        , 0.64102564, 0.5       , 0.05970149,
        0.57291667, 0.48417722, 0.53846154, 0.2962963 , 0.10526316,
        0.74698795, 0.44347826, 0.09878543],
       [0.57239057, 0.2997416 , 0.85470085, 0.75      , 0.47761194,
        0.42708333, 0.25316456, 0.23076923, 0.35185185, 0.52012384,
        0.15662651, 0.0173913 , 0.09149798],
       [0.6969697 , 0.27648579, 0.56410256, 0.47222222, 0.23880597,
        0.6875    , 0.79113924, 0.23076923, 0.49074074, 0.31372549,
        0.6746988 , 0.94782609, 0.49230769],
       [0.34006734, 0.46770026, 0.44444444, 0.55555556, 0.08955224,
        0.15625   , 0.43037975, 1.        , 0.28703704, 0.06604747,
        0.45783133, 0.87391304, 0.00242915],
       [0.73063973, 0.2377261 , 0.52136752, 0.39444444, 0.32835821,
        0.77083333, 0.85759494, 0.15384615, 0.53240741, 0.499484  ,
        0.73493976, 0.69130435, 0.97408907],
       [0.81481481, 0.23514212, 0.72649573, 0.28888889, 0.14925373,
        0.55729167, 0.7943038 , 0.15384615, 0.68981481, 0.36532508,
        0.91566265, 0.90434783, 0.77165992],
       [0.34343434, 0.20413437, 0.46153846, 0.52777778, 0.02985075,
        0.70833333, 0.84493671, 0.48076923, 0.44907407, 0.19401445,
        0.25301205, 0.67391304, 0.03238866],
       [0.48821549, 0.15762274, 0.48717949, 0.33333333, 0.56716418,
        0.06770833, 0.24367089, 0.13461538, 0.06481481, 0.21052632,
        0.3373494 , 0.        , 0.25748988],
       [0.53198653, 0.24031008, 0.72649573, 1.        , 0.82089552,
        1.        , 0.76265823, 0.13461538, 0.53703704, 0.13312693,
        1.        , 0.96086957, 0.54493927],
       [0.72390572, 0.25064599, 0.47863248, 0.23333333, 0.49253731,
        0.921875  , 0.88924051, 0.38461538, 0.71296296, 0.42002064,
        0.56626506, 0.90869565, 0.39109312],
       [0.48484848, 0.65374677, 0.70940171, 0.55555556, 0.32835821,
        0.140625  , 0.03797468, 0.88461538, 0.07407407, 0.36326109,
        0.46987952, 0.35652174, 0.20890688],
       [0.83838384, 0.24289406, 0.31623932, 0.22222222, 0.25373134,
        0.89583333, 0.92088608, 0.13461538, 0.62037037, 0.41692466,
        0.51807229, 0.88695652, 0.54493927],
       [0.87878788, 0.24289406, 0.39316239, 0.22222222, 0.17910448,
        0.66145833, 0.58544304, 0.23076923, 0.5462963 , 0.27244582,
        0.6746988 , 1.        , 0.5854251 ],
       [0.97306397, 0.30490956, 0.82905983, 0.44444444, 0.53731343,
        0.73958333, 0.84177215, 0.36538462, 0.54166667, 0.42724458,
        0.71084337, 0.59130435, 0.78380567],
       [0.49158249, 1.        , 0.62393162, 0.52777778, 0.02985075,
        0.16666667, 0.05379747, 0.63461538, 0.02777778, 0.57688338,
        0.07228916, 0.24782609, 0.2534413 ],
       [0.2962963 , 0.17312661, 0.1965812 , 0.22222222, 0.01492537,
        0.609375  , 0.63924051, 0.28846154, 0.44907407, 0.08668731,
        0.90361446, 0.63043478, 0.09392713],
       [0.6969697 , 0.24031008, 0.76068376, 0.58333333, 0.07462687,
        0.63541667, 0.19620253, 0.73076923, 0.68981481, 1.        ,
        0.10843373, 0.21304348, 0.24939271],
       [0.46464646, 0.49870801, 0.62393162, 0.55555556, 0.41791045,
        0.05208333, 0.27848101, 0.19230769, 0.21296296, 0.90196078,
        0.        , 0.07826087, 0.13603239],
       [0.93939394, 0.26356589, 0.5982906 , 0.17777778, 0.41791045,
        0.984375  , 0.92088608, 0.38461538, 0.54166667, 0.48400413,
        0.68674699, 0.67826087, 0.92145749],
       [0.01346801, 0.42894057, 0.57264957, 0.44444444, 0.17910448,
        0.79166667, 0.73101266, 0.34615385, 0.47685185, 0.12280702,
        0.38554217, 0.91304348, 0.2534413 ],
       [0.07070707, 0.32299742, 0.45299145, 0.33333333, 0.20895522,
        0.85416667, 0.56329114, 0.05769231, 0.25462963, 0.12280702,
        0.81927711, 0.72608696, 0.02672065]])

In [87]:
from sklearn.neural_network import MLPClassifier

In [88]:
model=MLPClassifier(hidden_layer_sizes=(150,100,45),activation='relu',max_iter=300,solver='adam')

In [89]:
model.fit(xtrain_transform,ytrain)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1109: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MLPClassifier(hidden_layer_sizes=(150, 100, 45), max_iter=300)

In [90]:
ypred=model.predict(xtest_transform)

In [91]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [92]:
accuracy=accuracy_score(ytest,ypred)
accuracy

0.9722222222222222

In [93]:
cm=confusion_matrix(ytest,ypred)
cm

array([[14,  0,  0],
       [ 0, 13,  0],
       [ 0,  1,  8]])